with open('/home/ubuntu/k12-education-research/drafts/literature_review_complete.tex', 'r') as f:
    content = f.read()

old_text = r"Outside of experimental settings, \citet{angrist1999} used Maimonides' Rule in Israel as a natural experiment, finding that class size reductions significantly improved reading and math scores."

new_text = r"""Outside of experimental settings, \citet{angrist1999} exploited Maimonides' Rule as a natural experiment to identify the causal effect of class size in Israel. Maimonides' Rule---derived from the 12th-century Talmudic scholar Rabbi Moses Maimonides---stipulates that a class must be split once enrollment exceeds 40 students. Under this rule, a school with 40 students has one class of 40, but a school with 41 students must form two classes of approximately 20--21 students each. This creates sharp, discontinuous variation in class size that is plausibly unrelated to student characteristics: a student enrolling in a cohort of 41 is effectively randomly assigned to a class half the size of a student in a cohort of 40, purely by virtue of one additional student registering. Because families cannot precisely manipulate enrollment to land just above or below the threshold, students on either side of each cutoff (40, 80, 120, etc.) are comparable in all observable and unobservable respects, providing a clean regression discontinuity design. \citet{angrist1999} found that class size reductions generated by this rule significantly improved reading and math scores, with effects comparable in magnitude to those found in the Tennessee STAR experiment."""

if old_text in content:
    content = content.replace(old_text, new_text)
    print("Maimonides explanation expanded successfully.")
else:
    print("Could not find the exact text to replace.")

with open('/home/ubuntu/k12-education-research/drafts/literature_review_complete.tex', 'w') as f:
    f.write(content)
